### ISSUE TITLE
Compatibility with JupyterLite

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/jupyterlab-myst#132]
What else do we need to do to have compatibility with JupyterLite @agoose77?

@stevejpurves prompted a few things to fix over here:
- https://github.com/jupyterlite/jupyterlite/pull/1021

It sounds like we might be do redo the trust mechanism, as that is server side? The `whl` is being added, but I am not sure if that addresses that?

**Comment by agoose77** [comment]
Yes, the trust mechanism is currently implemented on the notary (a server extension feature). We do this so that Markdown cells can be trusted. One the one hand, it might be that trust means different things in a JupyterLite context to a conventional server.

On the other hand, we might need to get this working. @jtpio we specifically want to control how notebooks are trusted upon loading from disk:

https://github.com/jupyter-server/jupyter_server/blob/702c248c314b032022f5da408fb0fb0ecbc8709f/jupyter_server/services/contents/filemanager.py#L381

Right now, I see https://github.com/jupyterlite/jupyterlite/blob/e9d591327b3db7cf6d6a7d564a5dabaa34fb60ae/packages/contents/src/contents.ts#LL666C23-L673C13 and https://github.com/jupyterlite/jupyterlite/blob/e9d591327b3db7cf6d6a7d564a5dabaa34fb60ae/packages/contents/src/contents.ts#L293, which suggests that we don't yet implement trust in jupyterlite.

**Comment by nthiery** [comment]
It would indeed be great to have myst in JupyterLite; actually, that's one thing that prevents
us from using myst in some small courses which we want to deploy by JupyterLite.

Just as a data point, here is the current log from the jupyterlite build with xeus-python
and jupyterlab-myst as dependency:

```
─ jupyterlab-myst   is uninstallable because it requires
   └─ jupyter_server >=1.6,<2  but there are no viable options
      ├─ jupyter_server [1.10.0|1.10.1|...|1.9.0] would require
      │  └─ tornado >=6.1 , which does not exist (perhaps a missing channel);
      ├─ jupyter_server [1.13.4|1.13.5|...|1.23.2] would require
      │  └─ pyzmq >=17 , which does not exist (perhaps a missing channel);
      └─ jupyter_server 1.13.5 would require
         └─ jupyter_core >=4.6.0 , which does not exist (perhaps a missing channel).
```

Cheers,

**Comment by nthiery** [comment]
Jupyterlab-myst running in JupyterLite :-)

![image](https://github.com/executablebooks/jupyterlab-myst/assets/545328/f7073e23-f4ea-43f7-91c7-a48e0dc99a25)

In short, with recent jupyterlite-xeus-python, I just had to throw in `jupyterlab-myst`
in the dependencies. Pretty cool. Let's see how robust this is!

## Details

Produced with this build environment:
```
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.1.0,<0.2.0
  - jupyterlite-xeus-python >=0.9.2,<0.10.0
```

and this Jupyterlite environment:
```
name: cours-python-jupyterlite

channels:
 - https://repo.mamba.pm/emscripten-forge
 - https://repo.mamba.pm/conda-forge

dependencies:
- ipycanvas
- ipywidgets
- jupyterlab-myst
```
