### ISSUE TITLE
Unknown directive: `eval-rst`

### ISSUE THREAD

**Issue by raphaelquast** [executablebooks/jupyterlab-myst#196]
## Description

Hey, while trying to couple some automatically generated python docs to myst-markdown files I realized that jupyterlab-myst does not seem to recognize the `{eval-rst}` directive (both in `.md` or `.ipynb` files).

If I render the same with `sphinx` and `myst_nb`, all works as expected.

Here's a snapshot of what I mean:

![image](https://github.com/executablebooks/jupyterlab-myst/assets/22773387/9af4bcb3-7b54-40a0-bd57-1ec9e2497cb9)

...here's the correct output I get with sphinx + myst_nb:

<img src=https://github.com/executablebooks/jupyterlab-myst/assets/22773387/cf711dc1-e191-4842-8d48-6d2d4d034824 width=25%>

Am I missing some config or is this directive simply not supported by jupyterlab-myst?

**Comment by rowanc1** [comment]
Thanks @agoose77. @raphaelquast -- we would be very interested to hear which features are not supported in MyST so that we can implement them!

**Comment by rowanc1** [comment]
I am hoping that we can take a pass on improving the markdown rendering of eval-snippets soon. Right now we are explicitly *not* parsing the markdown (and have the same problem as myst-nb), however, we have done some changes recently in mystmd.org to allow those to change and be fixed in jupyterlab-myst and the mystmd CLI!

Really exciting that you are using MyST in a lot of different places now and things are (generally!) working out. 🚀
