### ISSUE TITLE
Table of contents picks up on "#" marker.

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/jupyterlab-myst#90]
![image](https://user-images.githubusercontent.com/913249/219966415-3d4709b0-1dfb-4d63-8041-14fcd0a61a7a.png)

**Comment by rowanc1** [comment]
I think we might just need to add a `jp-InternalAnchorLink` on the anchor?

**Comment by rowanc1** [comment]
Ok, one solution is to change to a pilcrow `¶` marker instead of a hash `#`. That works -- I cannot for the life of me find where this gets removed.

**Comment by rowanc1** [comment]
Ok, this is fixed enough for now, we will pick this up in a next version of myst-to-react!

**Comment by agoose77** [comment]
I have ideas here, let me take a look!

**Comment by rowanc1** [comment]
Nice, thanks. :)

Might still change to a pilcrow for consistency!

**Comment by agoose77** [comment]
This is a bit of a rabbit warren, and I'm short on time so I've just done a cursory search.

It looks like the cell widget provides a mechanism for identifying headings in a cell:
https://github.com/jupyterlab/jupyterlab/blob/91751d133da99465ce0ef4f882e82a3f9de3b28d/packages/cells/src/widget.ts#L1854

We could overload that to provide MyST-friendly parsing.

However, there's also a mechanism for jumping to a cell by its heading ID, which is more hard coded:

JupyterLab's `StaticNotebook` parses headings via `getHeadingId`: https://github.com/jupyterlab/jupyterlab/blob/91751d133da99465ce0ef4f882e82a3f9de3b28d/packages/notebook/src/widget.ts#L2104

That function is interesting. It renders the heading using the `IMarkdownParser` interface that we don't implement (because it expects HTML as a return value).

**Comment by rowanc1** [comment]
I also tried to override the `heading` interface (with an empty list), and it did not work as expected. The cell headings also render differently depending on if the cell is being edited or is rendered.

I also noticed that it is copying the HTML, for example, using katex in the header will get duplicated. So perhaps the function is in the `sanitize` code somewhere?
